### ISSUE TITLE
username with capital letters

### ISSUE THREAD

**Issue by jgongil** [BrandwatchLtd/api_sdk#59]
I came across an issue when I use the token_path instead of the password to request my project:
BWProject(username=YOUR_ACCOUNT, project=YOUR_PROJECT)

When at the beginning I used  my username and password, the tokens.txt was generated with the username in lowercase (_read_auth_file). 
On the other hand, my username contains capital letters, meaning my user´s json will be returned with these capital letters in the username field, so the _test_auth() method will fail in bwproject.py.

I can think of ways to get around it by making it case sensitive, but I would appreciate some suggestions.

Many thanks in advance!

**Comment by hamishmorgan** [comment]
Thanks for raising this issue @jgongil 

Usernames are supposed to be case-insensitive in the platform so generally it shouldn't matter. The problem is in this project we are lowercasing it, but then comparing to the original case. The solution is to ensure comparisons are case-insensitive. Specifically here: https://github.com/BrandwatchLtd/api_sdk/blob/a51c133dafb1344351f5d7e4d8f5e03e8ed2da61/bwproject.py#L62

If you've got time to PR a fix I'll be happy to merge it. Otherwise I'll ask someone to take a look soon.

**Comment by jgongil** [comment]
Many thanks for your help @hamishmorgan 
I got around it by changing the comparison in _test_auth(self, username, token) as below, but at the same time I had to force/ensure that the BWUser is created with username in lower case.

`def _test_auth(self, username, token):
...        elif user["username"].lower() == username: #JG[20180904]: JSON can contain username in capital letters`

**Comment by hamishmorgan** [comment]
Why not lower-cased both sides?
```python
elif user["username"].lower() == username.lower()
```
That way people can use whatever case they like, and it just ignores it during comparison.

**Comment by jgongil** [comment]
Hi, yes we can, but that requires not only changing `_test_auth` but also:
`_read_auth`  which is also doing `if username in user_tokens`  (mixed case vs lower case)
